-- ============================================================================
-- MINI-PROJETO Módulo II — Pata Amiga
-- 03-dimensoes-construir.sql
-- Constrói: dim_categoria, dim_praca e bridge_loja_praca
-- ============================================================================

-- ============================================================================
-- DIM_CATEGORIA
-- Grão: uma grafia da origem (categoria_origem). 37 grafias + linha -1 = 38.
-- ============================================================================

DROP TABLE IF EXISTS dim_categoria CASCADE;
CREATE TABLE dim_categoria (
    sk_categoria      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_origem  VARCHAR(50) NOT NULL UNIQUE,
    nome_categoria    VARCHAR(30) NOT NULL,
    grupo_categoria   VARCHAR(20) NOT NULL
);

-- Linha -1 inserida ANTES do INSERT ... SELECT, para nenhuma FK ficar nula.
INSERT INTO dim_categoria (sk_categoria, categoria_origem, nome_categoria, grupo_categoria)
VALUES (-1, '(NAO INFORMADO)', 'Nao Informado', 'Nao Informado');

-- Carga a partir da grafia crua da staging.
INSERT INTO dim_categoria (categoria_origem, nome_categoria, grupo_categoria)
SELECT DISTINCT
    TRIM(s."CategoriaProduto") AS categoria_origem,
    CASE
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%MED%'    THEN 'Medicamento'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%PETISC%' THEN 'Petisco'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%RA%'     THEN 'Racao'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%HIG%'    THEN 'Higiene'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%BRINQ%'  THEN 'Brinquedo'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%ACESS%'  THEN 'Acessorio'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%SERV%'   THEN 'Servico'
        ELSE 'Nao Informado'
    END AS nome_categoria,
    CASE
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%MED%'    THEN 'Saude e Higiene'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%PETISC%' THEN 'Alimentacao'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%RA%'     THEN 'Alimentacao'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%HIG%'    THEN 'Saude e Higiene'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%BRINQ%'  THEN 'Bem-estar'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%ACESS%'  THEN 'Bem-estar'
        WHEN UPPER(TRANSLATE(TRIM(s."CategoriaProduto"),
                'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
                'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) LIKE '%SERV%'   THEN 'Bem-estar'
        ELSE 'Nao Informado'
    END AS grupo_categoria
FROM stg_pedido s
WHERE TRIM(s."CategoriaProduto") NOT IN (
    SELECT categoria_origem FROM dim_categoria WHERE sk_categoria = -1
);


-- ============================================================================
-- DIM_PRACA
-- Grão: uma praça de atendimento. 13 linhas + linha -1.
-- ============================================================================

DROP TABLE IF EXISTS dim_praca CASCADE;
CREATE TABLE dim_praca (
    sk_praca             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_praca            VARCHAR(20) NOT NULL UNIQUE, -- Aumentado para 20 por segurança
    nome_praca           VARCHAR(60) NOT NULL,
    regional             VARCHAR(30),
    domicilios_com_pet   INT
);

-- Correção aplicada: mudado de 'NAO_INFORMADO' (13 caracteres) para 'N/I' (3 caracteres)
INSERT INTO dim_praca (sk_praca, cod_praca, nome_praca, regional, domicilios_com_pet)
VALUES (-1, 'N/I', 'Nao Informado', 'Nao Informado', NULL);

INSERT INTO dim_praca (cod_praca, nome_praca, regional, domicilios_com_pet)
SELECT DISTINCT
    TRIM(sp."CodPraca")  AS cod_praca,
    TRIM(sp."NomePraca") AS nome_praca,
    TRIM(sp."Regional")   AS regional,
    CASE
        WHEN NULLIF(TRIM(sp."DomiciliosComPet"), '') IS NULL THEN NULL
        ELSE CAST(REPLACE(TRIM(sp."DomiciliosComPet"), '.', '') AS INTEGER)
    END AS domicilios_com_pet
FROM stg_loja_praca sp;


-- ============================================================================
-- BRIDGE_LOJA_PRACA
-- Ligação N:N loja x praça, com o fator de rateio do público.
-- ============================================================================

DROP TABLE IF EXISTS bridge_loja_praca CASCADE;
CREATE TABLE bridge_loja_praca (
    cod_loja        VARCHAR(20) NOT NULL, -- Aumentado para 20 por segurança
    sk_praca        INT NOT NULL REFERENCES dim_praca (sk_praca),
    fator_publico   DECIMAL(6,4) NOT NULL,
    PRIMARY KEY (cod_loja, sk_praca)
);

INSERT INTO bridge_loja_praca (cod_loja, sk_praca, fator_publico)
SELECT
    TRIM(sp."CodLoja") AS cod_loja,
    p.sk_praca,
    CAST(REPLACE(TRIM(sp."PercentualPublico"), ',', '.') AS DECIMAL(6,4)) AS fator_publico
FROM stg_loja_praca sp
JOIN dim_praca p
    ON TRIM(sp."CodPraca") = p.cod_praca;


-- ============================================================================
-- VALIDAÇÕES 
-- ============================================================================

SELECT 'dim_categoria (esperado 38)'        AS checagem, COUNT(*) AS resultado FROM dim_categoria
UNION ALL
SELECT 'nome_categoria distintos (esperado 8)', COUNT(DISTINCT nome_categoria) FROM dim_categoria
UNION ALL
SELECT 'dim_praca (esperado 13)',            COUNT(*) FROM dim_praca
UNION ALL
SELECT 'bridge_loja_praca (esperado 48)',    COUNT(*) FROM bridge_loja_praca;