-- ============================================================================
-- MINI-PROJETO Módulo II — Pata Amiga
-- 04-fato-pedido.sql
-- Constrói fato_pedido. Grão: 1 linha = 1 pedido. Esperado: 4.044 linhas.
-- ============================================================================

DROP TABLE IF EXISTS fato_pedido CASCADE;
CREATE TABLE fato_pedido (
    sk_pedido                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido                VARCHAR(20) NOT NULL,
    sk_tempo_pedido               INT NOT NULL,
    sk_tempo_entrega              INT NOT NULL,
    sk_loja                       INT NOT NULL,
    sk_categoria                  INT NOT NULL,
    houve_desconto                VARCHAR(15) NOT NULL,
    canal_pedido                  VARCHAR(20) NOT NULL,
    dt_pedido                     TIMESTAMP NOT NULL,
    qt_itens                      INT,
    vl_liquido                    DECIMAL(15,2),
    dias_integracao_separacao     INT,
    dias_separacao_nota           INT,
    dias_nota_despacho            INT,
    dias_despacho_entrega         INT,
    dias_total_ate_entrega        INT
);

INSERT INTO fato_pedido (
    numero_pedido,
    sk_tempo_pedido,
    sk_tempo_entrega,
    sk_loja,
    sk_categoria,
    houve_desconto,
    canal_pedido,
    dt_pedido,
    qt_itens,
    vl_liquido,
    dias_integracao_separacao,
    dias_separacao_nota,
    dias_nota_despacho,
    dias_despacho_entrega,
    dias_total_ate_entrega
)
SELECT
    TRIM(s."NumeroPedido") AS numero_pedido,

    -- sk_tempo_pedido
    CAST(TO_CHAR(
        TO_TIMESTAMP(NULLIF(TRIM(s."DtHoraPedido"), ''), 'MM/DD/YYYY HH12:MI AM'),
        'YYYYMMDD'
    ) AS INTEGER) AS sk_tempo_pedido,

    -- sk_tempo_entrega
    CASE
        WHEN NULLIF(TRIM(s."DtEntregaCliente"), '') IS NULL THEN -1
        ELSE CAST(TO_CHAR(TO_DATE(NULLIF(TRIM(s."DtEntregaCliente"), ''), 'YYYY-MM-DD'), 'YYYYMMDD') AS INTEGER)
    END AS sk_tempo_entrega,

    -- sk_loja
    COALESCE(l.sk_loja, -1) AS sk_loja,

    -- sk_categoria
    COALESCE(c.sk_categoria, -1) AS sk_categoria,

    -- houve_desconto
    CASE
        WHEN UPPER(TRIM(s."HouveDesconto")) IN ('S', 'SIM', '1', 'X', 'TRUE', 'V') THEN 'Sim'
        WHEN UPPER(TRIM(s."HouveDesconto")) IN ('N', 'NAO', '0', 'FALSE', 'F') THEN 'Nao'
        ELSE 'Nao Informado'
    END AS houve_desconto,

    -- canal_pedido
    CASE
        WHEN UPPER(TRIM(s."CanalPedido")) LIKE '%WHATS%' THEN 'WhatsApp'
        WHEN UPPER(TRIM(s."CanalPedido")) LIKE '%APP%'   THEN 'App'
        WHEN UPPER(TRIM(s."CanalPedido")) LIKE '%SITE%'  THEN 'Site'
        WHEN UPPER(TRIM(s."CanalPedido")) LIKE '%LOJA%'  THEN 'Loja Fisica'
        WHEN UPPER(TRIM(s."CanalPedido")) LIKE '%TEL%'   THEN 'Telefone'
        ELSE 'Nao Informado'
    END AS canal_pedido,

    -- dt_pedido
    TO_TIMESTAMP(NULLIF(TRIM(s."DtHoraPedido"), ''), 'MM/DD/YYYY HH12:MI AM') AS dt_pedido,

    -- qt_itens: CORRIGIDO contra traços '-', vazios ou strings como 'N/I' e 'n/d'
    CASE
        WHEN NULLIF(TRIM(s."QTD.Itens"), '') IS NULL 
          OR TRIM(s."QTD.Itens") IN ('-', 'N/I', 'n/d', 'N/D') THEN NULL
        ELSE CAST(REPLACE(TRIM(s."QTD.Itens"), '.', '') AS INTEGER)
    END AS qt_itens,

    -- vl_liquido
    CASE
        WHEN TRIM(REPLACE(s."ValorLiquidoPedido(R$)", 'R$', '')) IN ('', '-') THEN NULL
        WHEN s."ValorLiquidoPedido(R$)" LIKE '%,%'
            THEN CAST(REPLACE(REPLACE(REPLACE(REPLACE(s."ValorLiquidoPedido(R$)", 'R$', ''), ' ', ''), '.', ''), ',', '.') AS DECIMAL(15,2))
        ELSE CAST(REPLACE(REPLACE(s."ValorLiquidoPedido(R$)", 'R$', ''), ' ', '') AS DECIMAL(15,2))
    END AS vl_liquido,

    -- dias_integracao_separacao
    CASE
        WHEN NULLIF(TRIM(s."DtHoraIntegracaoERP"), '') IS NULL
          OR NULLIF(TRIM(s."Dt Separacao Estoque"), '') IS NULL THEN NULL
        ELSE (
            TO_DATE(NULLIF(TRIM(s."Dt Separacao Estoque"), ''), 'YYYY-MM-DD')
            - TO_TIMESTAMP(NULLIF(TRIM(s."DtHoraIntegracaoERP"), ''), 'MM/DD/YYYY HH12:MI AM')::date
        )
    END AS dias_integracao_separacao,

    -- dias_separacao_nota
    CASE
        WHEN NULLIF(TRIM(s."Dt Separacao Estoque"), '') IS NULL
          OR NULLIF(TRIM(s."DtNotaFiscal"), '') IS NULL THEN NULL
        ELSE (
            TO_DATE(NULLIF(TRIM(s."DtNotaFiscal"), ''), 'YYYY-MM-DD')
            - TO_DATE(NULLIF(TRIM(s."Dt Separacao Estoque"), ''), 'YYYY-MM-DD')
        )
    END AS dias_separacao_nota,

    -- dias_nota_despacho
    CASE
        WHEN NULLIF(TRIM(s."DtNotaFiscal"), '') IS NULL
          OR NULLIF(TRIM(s."Dt_Despacho_Transportadora"), '') IS NULL THEN NULL
        ELSE (
            TO_DATE(NULLIF(TRIM(s."Dt_Despacho_Transportadora"), ''), 'YYYY-MM-DD')
            - TO_DATE(NULLIF(TRIM(s."DtNotaFiscal"), ''), 'YYYY-MM-DD')
        )
    END AS dias_nota_despacho,

    -- dias_despacho_entrega
    CASE
        WHEN NULLIF(TRIM(s."Dt_Despacho_Transportadora"), '') IS NULL
          OR NULLIF(TRIM(s."DtEntregaCliente"), '') IS NULL THEN NULL
        ELSE (
            TO_DATE(NULLIF(TRIM(s."DtEntregaCliente"), ''), 'YYYY-MM-DD')
            - TO_DATE(NULLIF(TRIM(s."Dt_Despacho_Transportadora"), ''), 'YYYY-MM-DD')
        )
    END AS dias_despacho_entrega,

    -- dias_total_ate_entrega
    CASE
        WHEN NULLIF(TRIM(s."DtHoraIntegracaoERP"), '') IS NULL
          OR NULLIF(TRIM(s."DtEntregaCliente"), '') IS NULL THEN NULL
        ELSE (
            TO_DATE(NULLIF(TRIM(s."DtEntregaCliente"), ''), 'YYYY-MM-DD')
            - TO_TIMESTAMP(NULLIF(TRIM(s."DtHoraIntegracaoERP"), ''), 'MM/DD/YYYY HH12:MI AM')::date
        )
    END AS dias_total_ate_entrega

FROM stg_pedido s

-- Lookup de Loja
LEFT JOIN dim_loja l
    ON UPPER(TRANSLATE(
        CASE
            WHEN UPPER(TRANSLATE(REPLACE(REPLACE(TRIM(s."Loja-Nome"), '/SC', ''), '  ', ' '), 'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ', 'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) = 'PATA AMIGA BLUMENAL CENTRO' THEN 'PATA AMIGA BLUMENAU CENTRO'
            WHEN UPPER(TRANSLATE(REPLACE(REPLACE(TRIM(s."Loja-Nome"), '/SC', ''), '  ', ' '), 'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ', 'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) = 'PATA AMIGA FLORIPA NORTE' THEN 'PATA AMIGA FLORIANOPOLIS NORTE'
            WHEN UPPER(TRANSLATE(REPLACE(REPLACE(TRIM(s."Loja-Nome"), '/SC', ''), '  ', ' '), 'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ', 'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC')) = 'PATA AMIGA JGUA DO SUL' THEN 'PATA AMIGA JARAGUA DO SUL'
            ELSE REPLACE(REPLACE(TRIM(s."Loja-Nome"), '/SC', ''), '  ', ' ')
        END, 'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ', 'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC'
    )) = UPPER(TRANSLATE(l.nome_loja, 'áàâãäéèêëíìîïóòôõöúùûüçÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ', 'aaaaaeeeeiiiiooooouuuucAAAAAEEEEIIIIOOOOOUUUUC'))

-- Lookup de Categoria
LEFT JOIN dim_categoria c
    ON TRIM(s."CategoriaProduto") = TRIM(c.categoria_origem);


-- ============================================================================
-- VALIDAÇÕES DA FATO
-- ============================================================================

SELECT 'fato_pedido (esperado 4.044)' AS checagem, COUNT(*) AS resultado FROM fato_pedido;